Work/main tab controller
Rescado/rescado-app pull request #17
Opened 2022-02-10 15:41 UTC by Pekket

2022-02-11 09:58 UTC, Qrivi requested changes

2022-02-11 09:58 UTC, Qrivi commented on lib/src/views/main_view.dart
> +    super.initState();
Deze lijn moet naar boven cfr docs van initState:
> Implementations of this method should start with a call to the inherited method, as in `super.initState()`.

Bij alle andere controllers staan de argumenten ook op nieuwe lijnen en vsync als eerste fyi. 3 named argumenten imo beetje veel voor 1 lijn.

2022-02-11 09:58 UTC, Qrivi commented on lib/src/views/main_view.dart
> +      setState(() => _activeTab = nextTab);
Confused. Waarom een kopie van de state in provider bijhouden in de state van de widget?

2022-02-11 09:58 UTC, Qrivi commented on lib/src/services/controllers/main_tab_controller.dart
> +    state = tabIndex >= 0 && tabIndex < 3 ? tabIndex : 0; //RescadoConstants.mainViewInitialTabIndex;
Oversight?

2022-02-11 09:58 UTC, Qrivi commented on lib/src/views/profile_view.dart
> +                    label: 'Swipe time!',
Hardcoded label. Ok als dit toch overschreven wordt door je profile view branch (met localized label).

2022-02-11 09:58 UTC, Qrivi commented on lib/src/services/controllers/main_tab_controller.dart
> +    state = tabIndex >= 0 && tabIndex < 3 ? tabIndex : 0; //RescadoConstants.mainViewInitialTabIndex;
Geen fan van die `if/else` en die magic numbers hier. 

<details>
<summary>· Overbodig</summary>
Is in principe 100% overbodig want is geen fout die tijdens gebruik zou kunnen voorkomen, enkel door bad programming maar zelfs dat risico heb je beperkt met die `static const tabIndex`s. Performance-wise maakt het ongetwijfeld niets uit in gebruik op toestellen in 2022. Maar je check doen met `>`/`<` is trager dan 3x checken met `==` (tho toegegeven dan is het nóg meer hardcoded), en dat is nog trager dan gewoon de check die in praktijk altijd `true` gaat zijn weg te laten.</details>

<details>
<summary>· Tightly coupled</summary>
Ivm die hardcoded: als je nu een tab toevoegt in de toekomst moet je je conditie in die `if/else` gaan aanpassen ook. Dat is je controller tightly couplen aan je UI. 0/10. Jij gaat je eerste tijd nog herinneren die check aan te passen, maar iemand anders gaat aan zijn hoofd krabben omdat een nieuw scherm met `tabIndex = 4` naar de eerste tab gaat navigeren, zonder iets in de console te printen of zo, dus die persoon gaat tijd verliezen uit te zoeken waarom.</details>

<details>
<summary>· Error suppressing</summary>
En vind een default fallback tab ook minder logisch dan het equivalent van de IllegalArgumentException die de TabController zou throwen moest je toch een niet bestaande index meegeven (dan zie je direct dat er iets mis is, en wat er mis is).</details>

2022-02-11 09:58 UTC, Qrivi commented on lib/src/services/controllers/main_tab_controller.dart
> +    state = tabIndex >= 0 && tabIndex < 3 ? tabIndex : 0; //RescadoConstants.mainViewInitialTabIndex;
<details>
<summary> Ook niet 100% fan van die `tabIndex`es overigens lmao</summary>
want dan moet je code voor elke tab gaan aanpassen als je vooraan een tab wilt toevoegen bijvoorbeeld. :D Index van `_tabData` voor volgorde of die `value` argument van `onTap` zal altijd ok zijn.</details>

Maar ik geef maar suggesties. I don't mind dit te approven en het ooit zelf eens te refactoren. Dit is ok, zelfs met die comment over het hoofd gezien.

2022-02-11 09:58 UTC, Qrivi commented on lib/src/views/main_view.dart
> +      setState(() => _activeTab = nextTab);
~~Lijkt mij ook maar 1x die anonieme functie te moeten binden aan die listener maar nu bindt je elke keer `build()` opgeroepen wordt. Heb je gekeken of dit 1x is? (vb als je app even op achtergrodn houdt of de thememode aanpast -- weet niet wat allemaal `build()` triggert).~~

2022-02-11 09:58 UTC, Qrivi commented on lib/src/views/main_view.dart
> +      setState(() => _activeTab = nextTab);
~~Niet geprobeerd maar precies elke keer je de state in provider aanpast bindt je een anonieme functie aan die state, en in die functie zet je nog eens de state in je widget. Dat gaat een build van je widget triggeren, en dan in die fase bind je dezelfde functie nog eens opnieuw. Als ik dat puur in mijn hoofd afspeel en ik zet daar een console.log tussen, dan dan ga je elke keer je die `_activeTab` wijzigt 1x extra die console.log zien omdat je elke keer opnieuw en opnieuw en functie aanmaakt in memory en bindt? Klinkt als een memory leak maar ik kan mis zijn.~~

2022-02-11 09:58 UTC, Qrivi commented on lib/src/views/main_view.dart
> +      setState(() => _activeTab = nextTab);
👆 Zelf geprobeerd en in de Riverpod docs gelezen dat ie slim genoeg is te unbinden voor elke rebuild.

2022-02-11 10:50 UTC, Pekket commented on lib/src/views/main_view.dart
> +    super.initState();
Denk confused omdat Intellij automatisch een //TODO implement boven die super... zet

2022-02-12 01:38 UTC, Qrivi commented on lib/src/views/main_view.dart
> +    super.initState();
Zonde dat je de vsync niet als eerste argument gezet hebt maar ok. 😊

2022-02-12 01:40 UTC, Qrivi commented on lib/src/views/profile_view.dart
> +                    label: 'Swipe time!',
Thumbs down betekent dan gok ik dat het met je profile view localized zal worden.

2022-02-12 01:40 UTC, Qrivi approved these changes

2022-02-12 01:41 UTC, Qrivi commented on lib/src/views/main_view.dart
> +      setState(() => _activeTab = nextTab);
Niet meer van toepassing na laatste commit.

2022-02-12 01:42 UTC, Qrivi commented on lib/src/services/controllers/main_tab_controller.dart
> +    state = tabIndex >= 0 && tabIndex < 3 ? tabIndex : 0; //RescadoConstants.mainViewInitialTabIndex;
Geen check meer in laatste commit.

2022-02-14 12:04 UTC, Pekket commented on lib/src/views/main_view.dart
> +    super.initState();
Zelfde volgorde als ze beschreven staan in TabController lijkt me ook mooi 🐇

2022-02-14 12:04 UTC, merged